### ISSUE TITLE
Error with sidebar & alignment of text

### ISSUE THREAD

**Issue by ln123567** [GorvGoyl/Notion-Boost-browser-extension#139]
There's an error with the alignment of the text and the right sidebar. The text runs into the sidebar, and becomes partially blocked by it. 

*sidebar= the "outline" sidebar that appears when headings are used.

**Comment by h4rk8s** [comment]
https://github.com/GorvGoyl/Notion-Boost-browser-extension/issues/136

I have also reported this problem and there is a temporary solution. 78% width works best on MBP13

**Comment by GorvGoyl** [comment]
fixed!

**Comment by ln123567** [comment]
Hi! I'm still facing issues with the alignment. 

<img width="812" alt="github" src="https://user-images.githubusercontent.com/99376124/182024675-e5ea77c4-5aee-4568-bfe2-35cca288b6c4.png">

**Comment by GorvGoyl** [comment]
please wait for the extension update.

**Comment by ln123567** [comment]
Thanks!
