### ISSUE TITLE
bug: outline not showing anymore

### ISSUE THREAD

**Issue by JasonAri** [GorvGoyl/Notion-Boost-browser-extension#187]
Hi, I got a problem in 'outline' after installed React Developer Tools extension...

Like this...
<img width="351" alt="image" src="https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/96458454/3c75ef32-f593-46a5-9dfd-c12f4114ca2d">

Even Though I turned off React Developer Tools extension, it doesn't help...

**Comment by szh2022** [comment]
Same to me.

**Comment by stoneshi-1999** [comment]
Same to me. Does it because of the notion update or Chrome update?

**Comment by GorvGoyl** [comment]
thanks for reporting bug. Looks like an update from Notion side that broke the feature.. I'm looking into it and will release an update soon.

**Comment by RNCHEN** [comment]
same to me

**Comment by Bigshowzyb** [comment]
same to me

**Comment by djc80s** [comment]
same to me

**Comment by Ry0917design** [comment]
same to me!
It would be very appreciated if you could fix this bug as outline feature is SUPER!

**Comment by jiyun828** [comment]
Same to me

**Comment by zengqingxue** [comment]
the same to me. what happend?

**Comment by kkrepocom** [comment]
Same to me

**Comment by shengjie-chen** [comment]
Same to me. Outline is such a good feature. I'm waiting for a new update to fix it.

**Comment by TechSonnet** [comment]
Same to me. Outline is the most improtant feature. I am waiting for a net update to fix it.

**Comment by Zho24** [comment]
Me too, maybe Notion changed their code, web, API or something...
Please Please Please Please Please fix this bug, it's a very useful feature

**Comment by Velik857** [comment]
Same here, it's a SUPER useful function! Hope it can be solve as soon. Thanks!!

**Comment by RichardChenW** [comment]
Same to me , thanks for fixing this bug, this feature is really useful.

**Comment by u21h2** [comment]
same to me

**Comment by RichardChenW** [comment]
我已经收到您的来信，thank you！-Richard

**Comment by GrinZero** [comment]
same to me

**Comment by Phoebe0** [comment]
Same to me**,when will this bug be fixed**.I need this function.

**Comment by ITCJ** [comment]
Same to me

**Comment by pacemrc** [comment]
Same to me

**Comment by qiqingfu** [comment]
Hope to fix it soon, thank you very much

**Comment by GorvGoyl** [comment]
Fixed the bug and released it on Chrome web store v3.2.3. Please wait for it to go live.

https://chrome.google.com/webstore/detail/notion-boost/eciepnnimnjaojlkcpdpcgbfkpcagahd?hl=en-GB&authuser=0

**Comment by NOOMA-42** [comment]
does any still have same issue? I've removed it, installed again and it still not works

**Comment by JasonAri** [comment]
It works !!! Thanks a lot!

**Comment by NOOMA-42** [comment]
> Fixed the bug and released it on Chrome web store v3.2.3. Please wait for it to go live.
> 
> https://chrome.google.com/webstore/detail/notion-boost/eciepnnimnjaojlkcpdpcgbfkpcagahd?hl=en-GB&authuser=0

In my case the toggle heading still not work, looks like below
![截圖 2023-07-26 下午8 12 28](https://github.com/GorvGoyl/Notion-Boost-browser-extension/assets/35304302/8dbfad25-11ff-4fac-bf41-4753f8dcc4d6)
